POST http://localhost:3001/api/blogs/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1heW9pIiwiaWQiOiI2NmFiMmY5YjA5NzExZjI3NmRkYjZkMjMiLCJpYXQiOjE3MjI1MjM4NTJ9.VOjepkW5Ik1AHpG537vMqr4GF_-uAV0C-ShxTzf6s3g

{
  "title": "Crazy ass title2",
  "author": "the title maker",
  "url": "This is a url as well!"
}